# Generated by Django 4.0 on 2021-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_alter_relationship_unique_together'),
        ('posts', '0007_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.ManyToManyField(max_length=8, related_name='post_like', to='socialapp.Profile'),
        ),
    ]
