# Generated by Django 4.0 on 2021-12-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_alter_relationship_unique_together'),
        ('posts', '0008_remove_like_value_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='socialapp.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='socialapp.Profile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
