# Generated by Django 4.0 on 2021-12-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/images/default.png', null=True, upload_to='images'),
        ),
    ]
