# Generated by Django 4.0 on 2021-12-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_alter_profile_image'),
        ('posts', '0013_remove_post_dislikes_remove_post_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='socialapp.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='socialapp.Profile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
