# Generated by Django 4.0 on 2021-12-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_relationship_status_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver')},
        ),
    ]
