# Generated by Django 4.0 on 2021-12-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_alter_relationship_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
    ]
