# Generated by Django 4.0 on 2021-12-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_alter_relationship_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver')},
        ),
    ]
