# Generated by Django 4.0 on 2021-12-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_alter_relationship_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='avatar'),
        ),
    ]
