# Generated by Django 4.0 on 2021-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_alter_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar'),
        ),
    ]
